# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name longstitch_ci
    displayName: Create Anaconda environment

  - script: |
      conda install --yes --quiet -c conda-forge conda==4.11.0
      source activate longstitch_ci
      conda --version
      conda install --yes --quiet --name longstitch_ci -c conda-forge -c bioconda tigmint ntlink arcs pandas pytest samtools links==1.8.7
    displayName: Install Anaconda packages

  - script: |
      ./longstitch
    displayName: Test makefile help page

  - script: |
      source activate longstitch_ci
      cd tests
      pytest -vs longstitch_tests.py
    displayName: Run pytests
